package com.yanggang.autoinspection.contentsearch;

import com.yanggang.autoinspection.PostSearchPort;
import com.yanggang.autoinspection.content.inspectedpost.model.InspectedPost;
import com.yanggang.autoinspection.content.post.model.Post;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

@Component
public class PostSearchAdapter implements PostSearchPort {

    private final PostSearchRepository postSearchRepository;

    public PostSearchAdapter(PostSearchRepository postSearchRepository) {
        this.postSearchRepository = postSearchRepository;
    }

    @Override
    public void indexPost(InspectedPost post) {
        postSearchRepository.save(toDocument(post));
    }

    @Override
    public void deletePost(Long id) {
        postSearchRepository.deleteById(id);
    }

    public PostDocument toDocument(InspectedPost inspectedPost) {
        Post post = inspectedPost.getPost();
        return PostDocument.builder()
                .id(post.getId())
                .title(post.getTitle())
                .content(post.getContent())
                .categoryName(inspectedPost.getCategoryName())
                .tags(inspectedPost.getAutoGeneratedTags())
                .indexedDate(LocalDateTime.now())
                .build();
    }
}
