package com.yanggang.autoinspection.content.inspectedpost.model;

import com.yanggang.autoinspection.content.post.model.Post;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

@Getter
@NoArgsConstructor
public class InspectedPost {

    private Post post;
    private String categoryName;
    private List<String> autoGeneratedTags;
    private LocalDateTime inspectedDate;

    @Builder
    public InspectedPost(Post post, String categoryName, List<String> autoGeneratedTags, LocalDateTime inspectedDate) {
        this.post = post;
        this.categoryName = categoryName;
        this.autoGeneratedTags = autoGeneratedTags;
        this.inspectedDate = inspectedDate;
    }

    public static InspectedPost generate(
            Post post,
            String categoryName,
            List<String> autoGeneratedTags
    ) {
        return InspectedPost.builder()
                .post(post)
                .categoryName(categoryName)
                .autoGeneratedTags(autoGeneratedTags)
                .inspectedDate(LocalDateTime.now())
                .build();
    }

    @Override
    public String toString() {
        return "InspectedPost{" +
                "post=" + post +
                ", categoryName='" + categoryName + '\'' +
                ", autoGeneratedTags=" + autoGeneratedTags +
                ", inspectedDate=" + inspectedDate +
                '}';
    }
}
